### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by psp0001060** [mindslab-ai/nuwave2#10]
Hello,
I'm very interested in your great work!  
When I run `python trainer.py -r 629 -s`, I get an error like this.

` 
Validation sanity check:   0%|          | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\edwin\anaconda3\envs\nuwave\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\edwin\anaconda3\envs\nuwave\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'create_vctk_dataloader.<locals>.collate_fn'
Traceback (most recent call last):
  File "C:\Users\edwin\anaconda3\envs\nuwave\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

Process finished with exit code 1 `

I have inquired a lot of information, but it has not been solved. Do you have any good suggestions.
![image](https://user-images.githubusercontent.com/21292173/208296747-ebce97e5-fa16-4254-b66f-f2eb3d49c2b8.png)
![image](https://user-images.githubusercontent.com/21292173/208296783-96f9a53d-880c-4302-8070-7f7af3ce4e5f.png)

**Comment by psp0001060** [comment]
I take the funcation "collate_fn" out of  create_vctk_dataloader,it's work.
