### ISSUE TITLE
How much VRAM is necessary for this? 12 GB vram I got out of memory error

### ISSUE THREAD

**Issue by FurkanGozukara** [mindslab-ai/nuwave2#12]
the command i executed : python inference.py -c nuwave2_02_16_13_epoch=629.ckpt -i 5dk.mp3 --sr 16

here results 

![image](https://user-images.githubusercontent.com/19240467/217794177-33d0b400-7927-4a18-b9d4-009edfa8108f.png)

```
D:\86 se courses youtube kanali\upsample audio>python inference.py -c nuwave2_02_16_13_epoch=629.ckpt -i 5dk.mp3 --sr 16
Traceback (most recent call last):
  File "D:\86 se courses youtube kanali\upsample audio\inference.py", line 115, in <module>
    wav_recon, wav_list = model.inference(wav_l, band, args.steps, noise_schedule)
  File "C:\Python399\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\86 se courses youtube kanali\upsample audio\lightning_model.py", line 50, in inference
    signal, recon = self.model.denoise_ddim(signal, wav_l, band, logsnr_t, logsnr_s)
  File "D:\86 se courses youtube kanali\upsample audio\diffusion.py", line 54, in denoise_ddim
    noise = self.model(y, y_l, band, norm_nlogsnr)
  File "C:\Python399\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\86 se courses youtube kanali\upsample audio\model.py", line 215, in forward
    x, skip_connection = layer(x, band, noise_level)
  File "C:\Python399\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\86 se courses youtube kanali\upsample audio\model.py", line 173, in forward
    y_l, y_g = self.ffc1(y_l, y_g, band) # STFC
  File "C:\Python399\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\86 se courses youtube kanali\upsample audio\model.py", line 152, in forward
    out_xl = self.convl2l(x_l) + self.convg2l(x_g)
  File "C:\Python399\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Python399\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Python399\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.43 GiB (GPU 0; 12.00 GiB total capacity; 10.41 GiB already allocated; 0 bytes free; 10.42 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

**Comment by karljeon44** [comment]
failed with same error on 1080-ti (12GB)

but was able to run on gcp w/ A100 GPU, seems to require at least 20GB (for audio ~90seconds)

![Screenshot from 2023-07-20 17-26-11](https://github.com/mindslab-ai/nuwave2/assets/45057281/abef466f-3791-4210-81ab-987b32ca857e)
